# Generated by Django 5.1.15 on 2026-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_query', models.TextField()),
                ('task', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('task_confidence', models.FloatField(default=0.0)),
                ('input_valid', models.BooleanField(default=True)),
                ('execution_status', models.CharField(db_index=True, max_length=32)),
                ('result', models.TextField(blank=True, default='')),
                ('visual_evidence', models.JSONField(blank=True, default=dict)),
                ('execution_trace', models.JSONField(blank=True, default=dict)),
                ('total_duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Query Audit Log',
                'verbose_name_plural': 'Query Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
